version: '3.9'

networks:
  app-network:
    driver: bridge

services:

  # Web Application
  webapi:
    image: ${DOCKER_REGISTRY-}sgp-publicapi
    container_name: webapi
    build:
      context: .
      dockerfile: src/SGP.PublicApi/Dockerfile
    links:
      - "redis"
    networks:
      - app-network
    depends_on:
      - "sqlserver"
      - "redis"

  # Database Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Sxc56Nu9V
      - ACCEPT_EULA=Y
    networks:
      - app-network

  # Cache Server
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass Sxc56Nu9V
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - app-network
