version: '3.9'

networks:
  app-network:
    driver: bridge

services:

  # ASP.NET Core Web API Application
  sgp-webapi:
    image: ${DOCKER_REGISTRY-}sgp-webapi
    container_name: sgp-webapi
    build:
      context: .
      dockerfile: src/SGP.PublicApi/Dockerfile
    restart: unless-stopped
    links:
      - "redis"
    networks:
      - app-network
    depends_on:
      - "sqlserver"
      - "redis"

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    hostname: mssql
    container_name: sqlserver
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sxc56Nu9V
    networks:
      - app-network

  # Redis Cache Server
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass Sxc56Nu9V
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - app-network
