image: Visual Studio 2015

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: CodecovProject.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\SGP.Tests\bin\Debug\SGP.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[SGP.Tests*]*" -output:".\SGP.Tests_coverage.xml"
  - codecov -f "MyProject_coverage.xml"