name: Delete workflow runs

uses: Mattraks/delete-workflow-runs@v2.0.4
  with:    
    token: ${{ github.token }}   
    repository: ${{ github.repository }}    
    retain_days: 30
    keep_minimum_runs: 6
